contentTypes:
  banana:
    name: Banana
    description: A RIPE banana
    displayField: peel
    fields:
      -
        id: peel
        name: Peel
        required: true
        type: Text
        localized: true
        omitted: true
        disabled: false
        interface:
          widgetId: singleLine
  post:
    name: Post
    description: A post content
    displayField: title
    fields:
      -
        id: content
        interface:
          settings:
            helpText: Primary Post Content
          widgetId: markdown
        localized: true
        name: Content
        required: true
        type: Text
        validations: []
      -
        id: media
        interface:
          widgetId: assetLinkEditor
        linkType: Asset
        localized: true
        name: Media
        type: Link
        validations: []
      -
        disabled: false
        id: title
        interface:
          settings:
            helpText: Post Title
          widgetId: singleLine
        localized: true
        name: Title
        omitted: false
        required: true
        type: Symbol
        validations:
        - unique: true